<?php

/**
 * @file
 * Module file for the bpmn_io module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\eca\Entity\Eca;

/**
 * Implements hook_gin_content_form_routes().
 */
function bpmn_io_gin_content_form_routes(): array {
  return [
    'bpmn_io.add',
    'bpmn_io.convert',
    'entity.eca.edit_form',
  ];
}

/**
 * Implements hook_entity_operation().
 */
function bpmn_io_entity_operation(EntityInterface $entity): array {
  $operations = [];
  if ($entity instanceof Eca && \Drupal::service('bpmn_io.services.converter')->access($entity)->isAllowed()) {
    $operations['bpmn_io_convert'] = [
      'title' => t('Edit with BPMN.io'),
      'url' => Url::fromRoute('bpmn_io.convert', ['eca' => $entity->id()]),
      'weight' => 49,
    ];
  }
  return $operations;
}
