<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('focal_point', array(
  'fields' => array(
    'fid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'focal_point' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '7',
      'default' => '',
    ),
  ),
  'primary key' => array(
    'fid',
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('focal_point')
->fields(array(
  'fid',
  'focal_point',
))
->values(array(
  'fid' => '3',
  'focal_point' => '63,15',
))
->values(array(
  'fid' => '17',
  'focal_point' => '60,13',
))
->execute();
