default_patterns:
  headings: headings
  text: text
  lists: lists
  blockquote: blockquote
  rule: rule
  table: table
  alerts: alerts
  breadcrumbs: breadcrumbs
  forms: forms
  buttons: buttons
  pagination: pagination
default_colors:
  - ''
